// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {git_manager} from '../models';

export function GitClone(arg1:string,arg2:string):Promise<string>;

export function ListRepositories(arg1:string):Promise<Array<git_manager.RepositoryInfo>>;

export function Setup(arg1:string):Promise<string>;
