// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GitClone(arg1, arg2) {
  return window['go']['main']['App']['GitClone'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListRepositories(arg1) {
  return window['go']['main']['App']['ListRepositories'](arg1);
}

export function Setup(arg1) {
  return window['go']['main']['App']['Setup'](arg1);
}
