// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GitClone(arg1:string,arg2:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListRepositories(arg1:string):Promise<Array<main.RepositoryInfo>>;

export function Setup(arg1:string):Promise<string>;
